### ISSUE TITLE
Can't find snet/cnet files in release zip

### ISSUE THREAD

**Issue by luoyianwu** [KUR-creative/SickZil-Machine#49]
README.md says
`Unzip the release file and copy SickZil-Machine-0.1.1-pre0-win64-cpu-eng/resource/cnet and SickZil-Machine-0.1.1-pre0-win64-cpu-eng/resource/snet directories to SickZil-Machine/resource.
`
But I can't find those files in the release zip. At least not in `SickZil-Machine-0.1.1-pre0-win64-cpu-eng.zip` or `SickZil-Machine-0.1.1-pre0-win64-gpu-eng.zip`.

**Comment by KUR-creative** [comment]
`SickZil-Machine-0.1.1-pre0-win64-cpu-eng/resource/cnet` and `SickZil-Machine-0.1.1-pre0-win64-cpu-eng/resource/cnet` are directories. 

`SickZil-Machine-0.1.1-pre0-win64-cpu-eng/resource/cnet/cnet-0.1.0.pb` and `SickZil-Machine-0.1.1-pre0-win64-cpu-eng/resource/snet/snet-0.1.0.pb` are the files. Copy them to cloned repository.

Maybe README is somewhat confusing.

**Comment by luoyianwu** [comment]
Thanks for quick response.
I executed the following and I see no cnet or snet directories.
`
wget https://github.com/KUR-creative/SickZil-Machine/archive/v0.1.1-pre0/SickZil-Machine-0.1.1-pre0-win64-cpu-enu.zip
unzip SickZil-Machine-0.1.1-pre0-win64-cpu-enu.zip 
tree SickZil-Machine-0.1.1-pre0/resource
SickZil-Machine-0.1.1-pre0/resource
├── config.json
├── eraser.png
├── mask_all_btn.png
├── mask_btn.png
├── mask_off.png
├── mask_on.png
├── olds
│   ├── img_open.png
│   ├── mask_btn.old.png
│   ├── mask_btn.png
│   ├── mask_open.png
│   └── rmtxt_btn.png
├── pen.png
├── restore_btn.png
├── rmtxt_all_btn.png
├── rmtxt_btn.png
├── startup.png
├── szmc.ico
├── tools
│   ├── panning_off.png
│   ├── panning_on.png
│   ├── pen_tool_off.png
│   ├── pen_tool_on.png
│   ├── rect_tool_off.png
│   └── rect_tool_on.png
└── xcfs
    ├── mask_all_btn.xcf
    ├── mask_off.xcf
    ├── mask_on.xcf
    ├── mask_or_restore_btn.xcf
    ├── pen.xcf
    ├── rmtxt_all_btn.xcf
    ├── rmtxt_btn.xcf
    ├── startup.xcf
    └── tools.xcf

3 directories, 32 files
`

**Comment by KUR-creative** [comment]
**enu**?

wget https://github.com/KUR-creative/SickZil-Machine/archive/v0.1.1-pre0/SickZil-Machine-0.1.1-pre0-win64-cpu-enu.zip  <- Maybe **enu** is wrong

Your command has typo. Try 
`wget https://github.com/KUR-creative/SickZil-Machine/archive/v0.1.1-pre0/SickZil-Machine-0.1.1-pre0-win64-cpu-eng.zip` 

Perhaps  this **enu.zip** file I uploaded before is left in the Github. :joy:

**Comment by luoyianwu** [comment]
> **enu**?
> 
> wget https://github.com/KUR-creative/SickZil-Machine/archive/v0.1.1-pre0/SickZil-Machine-0.1.1-pre0-win64-cpu-enu.zip <- Maybe **enu** is wrong
> 
> Your command has typo. Try
> `wget https://github.com/KUR-creative/SickZil-Machine/archive/v0.1.1-pre0/SickZil-Machine-0.1.1-pre0-win64-cpu-eng.zip`
> 
> Perhaps this wrong **enu.zip** file I uploaded before is left somewhere in Github. 😂

Again, thanks for quick reply.
I really did make a typo!
But in fact, `SickZil-Machine-0.1.1-pre0-win64-cpu-eng.zip` and `SickZil-Machine-0.1.1-pre0-win64-cpu-enu.zip` produce identical md5 values (1cbded...), therefore are identical.
And I still can't find cnet and snet directories :'(

**Comment by KUR-creative** [comment]
I figured out what's going on. Maybe this is bug(or feature?) of **wget**
wget ignores big file like cnet-0.1.0.pb.

**Don't use wget, just click the below link to download SZMC.**

https://github.com/KUR-creative/SickZil-Machine/releases/download/v0.1.1-pre0/SickZil-Machine-0.1.1-pre0-win64-cpu-eng.zip

Or download from [Release page](https://github.com/KUR-creative/SickZil-Machine/releases).

**Comment by luoyianwu** [comment]
> I figured out what's going on. Maybe this is bug(or feature?) of **wget**.
> wget ignores big file like cnet-0.1.0.pb in default.
> 
> **Don't use wget, just click the below link to download SZMC.**
> 
> https://github.com/KUR-creative/SickZil-Machine/releases/download/v0.1.1-pre0/SickZil-Machine-0.1.1-pre0-win64-cpu-eng.zip
> 
> Or download other versions from [Release page](https://github.com/KUR-creative/SickZil-Machine/releases).

Hi,
half an hour ago I tried again the exact same procedure in my second comment (with wget), and it finally downloaded the right zip with cnet and snet. I think the problem might be the back-end redirection mechanism fetching the wrong file. I'll close this issue.
