### ISSUE TITLE
마스크 생성 실행시 튕김현상이 일어납니다.

### ISSUE THREAD

**Issue by abcmario** [KUR-creative/SickZil-Machine#72]
[sikzil_test.zip](https://github.com/KUR-creative/SickZil-Machine/files/3848471/sikzil_test.zip)
압축파일은 식질머신 테스트 영상을 녹화해서 올린것입니다.
증상은 제목 그대로 이미지에서 마스크 생성을 실행할 시 자동으로 마스크를 생성하지 못하고 강제종료가 일어나는 현상이 나타납니다.
처음에는 다운로드 받을 때 누락이 되서 정상적인 실행이 안되는 것인가 했는데 몇번 다시 받아봐도 같은 현상이 나타났습니다.
다운로드한 파일은 <SickZil-Machine-0.1.1-pre0-win64-gpu-kor>입니다. 혹시라도 필요한 정보가 있다면 능력껏 제공해 드리겠습니다. 감사합니다.

**Comment by KUR-creative** [comment]
cmd를 이용하여 식질머신이 저장된 폴더 기준으로 `SickZil-Machine-0.1.1-pre0-win64-gpu-kor\main\SickZil-Machine-0.1.1-pre0-win64-gpu-kor.exe` 를 실행하면 cmd에 출력되는 디버깅 로그를 확인할 수 있습니다. 그 로그를 이슈에 올려주실 수 있나요?

1. 먼저 탐색기를 이용하여 `SickZil-Machine-0.1.1-pre0-win64-gpu-kor\main\`으로 들어갑니다.

![image](https://user-images.githubusercontent.com/20921187/68914537-3dbb4180-07a2-11ea-8145-db756a4ccaaf.png)

2. 그 위치에서 cmd나 파워쉘을 실행합니다. (cmd의 `cd` 명령으로 실행파일 SickZil-Machine-0.1.1-pre0-win64-gpu-kor.exe 가 있는 폴더로 이동할 수도 있습니다. )

![image](https://user-images.githubusercontent.com/20921187/68914631-8bd04500-07a2-11ea-9f3f-6805cb682192.png)

3. cmd나 파워쉘에 `.\SickZil-Machine-0.1.1-pre0-win64-gpu-kor.exe`  명령을 입력하고 엔터를 누르면 프로그램이 실행됩니다.

![image](https://user-images.githubusercontent.com/20921187/68914696-be7a3d80-07a2-11ea-8c3b-d1a17b8a3eec.png)


4. 마스크를 생성하고 강제 종료될 때 cmd에 출력되는 로그를 복사합니다. cmd를 드래그 하고 엔터키를 누르면 복사할 수 있습니다. (스크린샷을 올리셔도 됩니다)

![image](https://user-images.githubusercontent.com/20921187/68914741-e073c000-07a2-11ea-851c-a31ef6e2f8f8.png)


혹시 특정 이미지가 문제가 되는 것이라면 그 이미지를 올려주시거나 kur.creative.org@gmail.com 으로 보내주시면 감사하겠습니다.

**Comment by abcmario** [comment]
![test_result](https://user-images.githubusercontent.com/57631461/68961289-5f094580-0815-11ea-988e-4f791df70b47.png)
조언해주신대로 실행하였더니 말씀하신대로 워닝이 뜨면서 로그가 남네요.
도움이 되길 바라겠습니다.

**Comment by KUR-creative** [comment]
https://github.com/KUR-creative/SickZil-Machine/releases
여기 보시면 요구사항으로 

- CUDA(capability >= 3.5)를 지원하는 NVIDIA 그래픽 카드
- 최신 NVIDIA driver

가 있습니다.
그래픽 카드가 NVIDIA 카드인지 확인해보시고
맞다면 최신 드라이버로 업데이트 해보세요.

NVIDIA 카드가 아니거나 
[CUDA capatibility](https://developer.nvidia.com/cuda-gpus)가 너무 낮으면 실행되지 않을 수 있습니다.
그러면 cpu 버전을 사용해보세요.

그래도 문제가 생기신다면 다시 코멘트 해주세요.
문제가 해결되면 이슈를 close해 주시면 감사하겠습니다.

**Comment by abcmario** [comment]
감사합니다! 덕분에 정상적으로 돌아가는 것 같습니다. 순조로운 개발 되시길 바랍니다.
