### ISSUE TITLE
About user experience

### ISSUE THREAD

**Issue by LuckyRabbitFeet** [KUR-creative/SickZil-Machine#77]
The software will spoof and become unresponsive when performing AI editing. I think adding a loading animation can make the user experience feel better.
like this:
![unresponsive](https://user-images.githubusercontent.com/32757528/70643764-8d473d00-1c7c-11ea-8ed0-4b2a37d22391.png)

**Comment by KUR-creative** [comment]
I know this problem.. #12 
So I report this issue duplicated and close.

Currently you can follow the progress in the console running with the GUI.

![terminal](https://user-images.githubusercontent.com/20921187/70671437-5fcfb300-1cbf-11ea-8663-a966edeefa45.png)
(screenshot from https://www.myelf.club/index.php/archives/157/)

But Yeah.. It sucks. 

I'll make AI processing asynchronously. 
So in next version, user can edit mask while the operation is in progress.
